name: restaurant
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  square_in_app_payments: ^1.3.0
  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
  webview_flutter: ^0.3.21
  razorpay_flutter: ^1.2.0
  fluttertoast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/
